### ISSUE TITLE
make .childProcess part of the public API

### ISSUE THREAD

**Issue by cdaringe** [zentrick/cross-spawn-promise#50]
# problem statement

- sometimes i need access to the `childProcess` handle because i have long running processes (e.g. processes with watch)

# solution

- `childProcess` is exposed, but it would be nice if we could do something in the docs to let user's known it's a first class citizen, and not a private API in this lib

**Comment by timdp** [comment]
Agreed. We added this in #43 but the docs didn't get updated. I'll take a look.

**Comment by cdaringe** [comment]
Wow thanks!

**Comment by timdp** [comment]
You're welcome!
